kirtonBCIlab/bci-essentials-python

- bci_essentials/bci_data.py
- bci_essentials/classification.py
- env/bci_essentials_env.yml
- env/bci_online.yml
- examples/switch_offline_test.py
Added a trial started print statement to bci_data
> Minor P300 fixes, plus update to yml

- .gitignore
- examples/ssvep_offline_test.py
- setup.py
Added setup,
removed the weird space at end of ssvep_offline_test.py
> Added setup

- bci_essentials/bci_data.py
- bci_essentials/channel_selection.py
- bci_essentials/classification.py
- bci_essentials/signal_processing.py
- examples/mi_offline_test.py
- examples/p300_offline_test.py
- examples/ssvep_offline_test.py
- mi_ch_select_test.ipynb
- mi_ch_select_test.py
- p300_ch_select_test.py
- profile.json
> Integrating channel selection

- LICENSE
This is a test to make sure build is working / prep for demoing PR process to team.
Don't merge this, I need the example.
> Updating copyright year

- bci_essentials/signal_processing.py
Updated docstrings in document to be compliant with NumPy format and PEP257 compliant
> Updated docstrings

- bci_essentials/signal_processing.py
Some changes from the first merge of branch to main were lost – putting those back in
> Updated docstrings post black formatting

- bci_essentials/visuals.py
Updated docstrings formatting to NumPy standard
> Updated docstrings formatting

- bci_essentials/resting_state.py
- bci_essentials/signal_processing.py
- bci_essentials/visuals.py
Updated docstrings for `resting_state` for automatic API generation. Also made minor updates to `visuals` and `signal_processing` to make documents stylistically consistent, and a minor error introduced in `signal_processing` on the last PR.
> Docstrings resting_state

- bci_essentials/channel_selection.py
Updated and created docstrings for NumPy formatted API documentation generation
> Docstrings channel selection

- LICENSE
- bci_essentials/classification/__init__.py
- bci_essentials/classification/erp_rg_classifier.py
- bci_essentials/classification/generic_classifier.py
- bci_essentials/classification/mi_classifier.py
- bci_essentials/classification/null_classifier.py
- bci_essentials/classification/ssvep_basic_tf_classifier.py
- bci_essentials/classification/ssvep_riemannian_mdm_classifier.py
- bci_essentials/classification/switch_deep_classifier.py
- bci_essentials/classification/switch_mdm_classifier.py
Branched from `B4K_86-license`
Updated docstrings in all classification submodules, filling in information with what is there and putting a template when information on information on descriptions, parameters or returns are unavailable.
> Updated docstrings in classification submodules

- bci_essentials/channel_selection.py
- bci_essentials/classification/mi_classifier.py
- examples/mi_ch_select_test.py
Also fixed the issue that on "silent" some channel selection methods were still printing
> Fixed print_output in stopping criterion

- environment.yml
To test, the conda environment needs to be recreated:
```
git clean -fdx
conda env remove -n bci
conda env create -f ./environment.yml 
conda activate bci
pip install -e .
```
> Upgrading to Python 3.10

- bci_essentials/resting_state.py
- examples/rs_offline_test.py
This fixes rs offline test so that it runs. The issue was in the get_alpha_peaks function in resting state.
> Fix rs offline test

- bci_essentials/classification/erp_rg_classifier.py
- bci_essentials/classification/generic_classifier.py
- bci_essentials/classification/mi_classifier.py
- bci_essentials/classification/null_classifier.py
- bci_essentials/classification/ssvep_basic_tf_classifier.py
- bci_essentials/classification/ssvep_riemannian_mdm_classifier.py
- bci_essentials/classification/switch_deep_classifier.py
- bci_essentials/classification/switch_mdm_classifier.py
- bci_essentials/eeg_data.py
- bci_essentials/erp_data.py
- examples/mi_ch_select_test.py
- examples/mi_offline_test.py
- examples/mi_unity_backend.py
- examples/p300_ch_select_test.py
- examples/p300_offline_test.py
- examples/p300_unity_backend.py
- examples/rs_offline_test.py
- examples/ssvep_offline_test.py
- examples/ssvep_offline_test_tf.py
- examples/ssvep_unity_backend.py
- examples/ssvep_unity_backend_tf.py
- examples/switch_offline_test.py
- examples/switch_unity_backend.py
- tests/test_classifier_save.py
- tests/test_eeg_data.py
- tests/test_smoke.py
- tutorials/01_show_me_the_data.ipynb
This was mostly done by changing class names.
Thank goodness for find and replace.
> Updated to standard naming conventions

- bci_essentials/eeg_data.py
- bci_essentials/erp_data.py
- examples/mi_ch_select_test-debug_log_level.py
- examples/mi_ch_select_test.py
- examples/mi_offline_test.py
- examples/mi_unity_backend.py
- examples/mne/p300_mne_plotting.py
- examples/p300_ch_select_test.py
- examples/p300_offline_test.py
- examples/p300_unity_backend.py
- examples/rs_offline_test.py
- examples/ssvep_offline_test.py
- examples/ssvep_offline_test_tf.py
- examples/ssvep_unity_backend.py
- examples/ssvep_unity_backend_tf.py
- examples/switch_offline_test.py
- examples/switch_unity_backend.py
- tests/test_classifier_save.py
- tests/test_eeg_data.py
- tests/test_smoke.py
[B4K-230](https://bci4kids.atlassian.net/browse/B4K-230)
The EegData / ErpData were changed so that an external caller can control the processing loop.  See spike notes [here]( https://bci4kids.atlassian.net/wiki/spaces/BE/pages/67436545/Sharing+the+loop).  The gist is this:
setup(...) is used to control how the processing loop will function
run() will execute the processing loop according to online/offline rules
step() will execute a single step of the processing loop
I decided to keep the "max_loops" argument in the run() function as it doesn't make much sense outside of that context.
Tests and examples were updated.
> Bessy step run

- bci_essentials/channel_selection.py
- bci_essentials/classification/erp_rg_classifier.py
- bci_essentials/classification/generic_classifier.py
- bci_essentials/classification/mi_classifier.py
- bci_essentials/classification/ssvep_basic_tf_classifier.py
- bci_essentials/classification/switch_deep_classifier.py
- bci_essentials/classification/switch_mdm_classifier.py
- bci_essentials/eeg_data.py
- bci_essentials/erp_data.py
- bci_essentials/resting_state.py
- bci_essentials/session_saving.py
- bci_essentials/signal_processing.py
- bci_essentials/visuals.py
Replaced "straight array indexing to action" in BessyPy with an intermediate variable with a descriptive name, so it is easier to understand what is being pulled out of an array and for what reason.
E.g.:
Before: `if self.marker_data[self.marker_count][0] == "Done with all RS collection": ...`
Now:
```
current_step_marker = self.marker_data[self.marker_count][0]
if current_step_marker = "Done with all RS collection" ...
```
Within eeg_data.py and erp_data.py, I have repeated the variable definition `current_step_marker = self.marker_data[self.marker_count][0]` rather than putting it once at the top of the while loop. I had tried putting the variable definition for `current_step_marker` just once at the top the loop, because I had thought `self.marker_data` data container wouldn't change …
> B4k213  arrayindex to variable

- bci_essentials/io/lsl_sources.py
[B4K-257](https://bci4kids.atlassian.net/browse/B4K-257)
ThinkLab needed a way to choose a stream instead of just picking the first one.  I updated the LSL sources to optionally take a stream.  I also did a bit of cleanup to avoid repetition.
> Optionally provide LSL stream to source

- bci_essentials/channel_selection.py
- bci_essentials/classification/mi_classifier.py
- bci_essentials/classification/ssvep_riemannian_mdm_classifier.py
- bci_essentials/erp_data.py
- bci_essentials/session_saving.py
- bci_essentials/signal_processing.py
- bci_essentials/visuals.py
- examples/mi_ch_select_test-debug_log_level.py
- examples/mi_ch_select_test.py
- pyproject.toml
Test PR for debugging the build.
> Updating black formatter settings

- bci_essentials/classification/generic_classifier.py
- bci_essentials/erp_data.py
Changed output from ERP data to match changes made during the MindTV project
> Fix for predictions

- bci_essentials/classification/erp_single_channel_classifier.py
- bci_essentials/eeg_data.py
- bci_essentials/erp_data.py
- bci_essentials/utils/reduce_to_single_channel.py
- examples/p300_SingleChannelERP_offline_test.py
@ekinney-lang asked me to add support for single channel BCI, specifically P300 and the Idun Guardian. 
What's new.
1. ERPSingleChannelClassifier which just used shrinkage LDA using all samples from each epoch as features. We can build a better classifier later, but not without data. I tested this one on single channels of the p300_data example on here and got ~55% accuracy, much better than the ~11% chance, so that is a good start.
2. Added a transformer (sklearn pipeline style) that reduces an X with many channels down to an X with one channel. This helps ERPSingleChannelClassifier to not die if it accidentally gets passed more channels.
3. Testing with the Idun guardian highlighted some challenges with Bessy. First, if there is no EEG data by the "step" of EegData or ErpData then …
> Add ear eeg support

- .github/workflows/publish-on-tag.yml
- .github/workflows/pull-request-build.yml
- .github/workflows/push-code-files-to-APIdocs-repository.yml
Another test PR to see if the actions work...
> Updating actions/checkout@v3 to v4

- bci_essentials/bci_controller.py
- bci_essentials/data_tank/data_tank.py
Also fixing an oopsie associated with using find and replace to change "eeg_data" into "bci_controller"
> __raw_eeg in data tank was concatenating along wrong axis

- bci_essentials/paradigm/mi_paradigm.py
- examples/mi_offline_test.py
Also removed Riemannian channel selection from the MI_offline_example because I am unsure of it.
> Assigned lowcut and highcut parameters.

- bci_essentials/bci_controller.py
- bci_essentials/classification/generic_classifier.py
- bci_essentials/data_tank/data_tank.py
- examples/eeg_lsl_sim.py
- tests/test_generic_classifier__check_classifier_ready_for_fit.py
This PR adds some stability improvements to Bessy Python. It also adds functionality to eeg_lsl_sim.py to simulate packet loss or otherwise dropped transmission. (To simulate EEG with lost packets, use python examples/eeg_lsl_sim.py now 8 mi packetloss).
First, Bessy now checks when processing an epoch (for paradigms that classify on epoch) or trial (for paradigms that classify on trial) if the EEG timestamps for that trial/epoch are consistently increasing by approximately the sampling period. If not, it throws out that epoch/trial. It will also throw out an epoch/trial if Bessy has not received any EEG. Otherwise, it assumes that more is coming and waits for more EEG.
Test this online in MI, P300, and SSVEP. You can use the simulated packet loss in eeg_lsl_sim.py or just quit and …
> B4K219_221_222_224 – Bessy stability test and improve

- bci_essentials/bci_controller.py
This is for [B4K-351](https://bci4kids.atlassian.net/browse/B4K-351). It is a follow-up from the [Spike on Markers in Bessy Python](https://bci4kids.atlassian.net/wiki/spaces/BE/pages/257392641/Spike+on+Markers+in+Bessy+Python) as a demo of the enumerated types approach. 
1. Added a `MarkerTypes` enumeration to `bci_controller.py`. This defines the strings for each of the different Command Marker types. (Event markers are not included as they are not explicit strings).
2. Created a dictionary `marker_methods` in the init method to assign each marker enum to a method.
3. Moved the logic for handling the Event markers from the `step()` method into its own method.
4. Moved the logic for handling the Command markers from the `step()` method into separate methods. Using the marker methods …
> B4K351 – Demo of enumerated types for clearer messaging

- bci_essentials/bci_controller.py
This addresses Jira task [B4K-359: Streamline logic of marker handling in bci_controller.step() and handle silent failures in marker parsing](https://bci4kids.atlassian.net/browse/B4K-359). The main issues were that the logic wasn’t as clear as it could be, and some silent failures (i.e. marker that is neither command or event) could go unnoticed.
This PR improves the logic and clarity of how command and event markers are parsed in BciController.step(). Additionally there are modifications it logging that help devs and users understand what is happening when something breaks.
- Refactored the marker processing in the main loop to make the difference between command and event markers more obvious.
```
def step(self):
"""Runs a single BciController processing step.
See setup() for …
```
> B4k359  – Improve logic and clarity of marker handling in BciController.step()

- bci_essentials/bci_controller.py
- ensured `continue_flag` is assigned in all cases, as it would result in a crash
- added dedicated check for empty markers, distinguishing them from unknown and ignoring them completely
> Fix unknown marker handling

- bci_essentials/channel_selection.py
- bci_essentials/classification/erp_rg_classifier.py
- bci_essentials/classification/erp_rg_classifier_hyperparamgridsearch.py
- bci_essentials/classification/erp_single_channel_classifier.py
- bci_essentials/classification/generic_classifier.py
- bci_essentials/classification/mi_classifier.py
- bci_essentials/classification/ssvep_riemannian_mdm_classifier.py
- bci_essentials/classification/switch_mdm_classifier.py
Fixes the issue where accuracy is reported based on the classifier fit with all data, leading to much greater estimates of performance.
> Fix accuracy reporting
